[package]
name = "chip8emu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.7.0"
winit = "0.26.1"
glam = "0.20.2"

ncurses = "5.101.0"

rand = "0.8.5"
